_target_: vqvae.pl_modules.pl_module.VQGANLitModule
cfg:
  model:
    embedding_dim:   256
    codebook_size:   8192
    beta:            0.25
    n_res_blocks:    2
    channel_base:    128
    channel_max:     512
    f_downsample:    16
    lambda_rec:      1.0
    lambda_perc:     1.0
    lambda_gan:      0.1
    image_channels:  3
    start_channels:  128
    _recursive_: false

  pl:
    _recursive_: false
    lr:           3e-4
    betas:        [0.9, 0.95]
    gradient_clip_val: 1.0
    checkpoint_every_n: 5
    gradient_accumulation_steps: 1
    optimizer: adamw
    scheduler: cosine
    max_steps: 10000

    loss:
      recon_weight:        1.0
      perceptual_weight:   1.0
      vq_weight:           1.0
      adversarial_weight:  0.8
      disc_start:          10_000
