# conf/hydra/default.yaml
run:
  dir: .
sweep:
  dir: .
  subdir: .
output_subdir: null

job:
  env_set:
    WANDB_START_METHOD: thread
    WANDB_DIR: ${oc.env:PROJECT_ROOT,${hydra:runtime.cwd}}/wandb

defaults:
  - override job_logging: none
  - override hydra_logging: none
