max_epochs:        300
precision:        16   # mixed‑precision
accelerator:      auto
lr:               3e-4   # G & E
lr_d:             1e-5   # D
betas:            [0.5, 0.9]
gradient_clip_val: 1.0
checkpoint_every_n: 5
gradient_accumulation_steps: 1
optimizer: adamw
scheduler: cosine
max_steps: 10000

loss:
  recon_weight:        1.0   # L1
  perceptual_weight:   1.0   # LPIPS‑VGG
  vq_weight:           1.0   # codebook/commitment
  adversarial_weight:  0.8   # GAN term (matches disc_weight)