# conf/trainer.yaml
_target_: pytorch_lightning.Trainer
accelerator: gpu
devices: 8
strategy: ddp_find_unused_parameters_true

max_epochs: 50
precision: "bf16-mixed"

logger:
  - _target_: pytorch_lightning.loggers.WandbLogger
    project: vqgan-from-scratch
    name: ${name}
    save_dir: .
    log_model: true

callbacks:
  - _target_: pytorch_lightning.callbacks.RichProgressBar
  - _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: -1
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val/vq_loss
    mode: min
    save_top_k: 1
    save_last: true
    dirpath: ${hydra:runtime.cwd}/checkpoints
    filename: vqgan-{epoch:02d}-{step:06d}